### ISSUE TITLE
Move the repo from `Clikengo` to `FoundationDB-rs`

### ISSUE THREAD

**Issue by PierreZ** [foundationdb-rs/foundationdb-rs#1]
This meta-issue is set to keep track of the work that needs to be done in order to complete the move from `Clikengo` to `foundationdb-rs`

### Why moving the repo?

The original repo, [Clikengo/foundationdb-rs](https://github.com/Clikengo/foundationdb-rs/) is no longer active. There is [no activity from Clikengo's employees](https://github.com/Clikengo/foundationdb-rs/issues/239) on any repo owned by Clikengo. PRs are stacking and cannot be merged, as former maintainers like @Speedy37 only have simple contributor rights to the project. Also, developers like @Diggsey or @rajivr have forked the repo and are using their fork with various branches and/or fixes.

A change of main repository to merge the efforts seems the most logical to us for the sustainability of the project and the community. The overall goal is to improve and maintain the Rust binding as a community-maintained bindings. At that point, it could even be moved to [the official FoundationDB's Github org](https://github.com/foundationDB).

## Tasks

- [x] add maintainers from crates.io back. I added back the owners of the crate(according to [crates.io](https://crates.io/crates/foundationdb)) @bluejekyll, @Speedy37 and @yjh0502 as maintainers of the repo. Feel free to ping me if you don't want to be maintainer.
- [x] recreate codecov.io integration
- [x] Add other maintainers. Did I forget someone?
- [x] Change mention of Clikengo in the repo

Feel free to comment if you are seeing other tasks that needs to be done.
